### ISSUE TITLE
I think we should have a discussion channel for this repository

### ISSUE THREAD

**Issue by RobCFraser** [JessFraser/fpl-data-analysis#9]
@Hi @JessFraser  - can we enable discussions for this repository. I used them at my last company, and they were really useful

- [ ]  Jess has added discussions

**Comment by JessFraser** [comment]
We have a discussion channel, do you mean linking slack?

**Comment by RobCFraser** [comment]
Aha - you are right. I was doing this to practise setting up and assigning an issue. I will close the issue
